document.addEventListener('DOMContentLoaded', () => {
    const numberInput = document.getElementById('numberInput');
    const addNumberBtn = document.getElementById('addNumberBtn');
    const resetBtn = document.getElementById('resetBtn');
    const resultsList = document.getElementById('resultsList');
    const latestNumberAnalysisDiv = document.getElementById('latestNumberAnalysis');
    const hitFrequencyDiv = document.getElementById('hitFrequencyAnalysis');
    const hotColdDiv = document.getElementById('hotColdAnalysis');
    const lastSeenDiv = document.getElementById('lastSeenAnalysis');
    const repeaterSleepersDiv = document.getElementById('repeaterSleepersAnalysis');
    const distanceAnalysisDiv = document.getElementById('distanceAnalysis');
    const basicPropsDiv = document.getElementById('basicPropsAnalysis');
    const positionalPropsDiv = document.getElementById('positionalPropsAnalysis');
    const advancedTablePropsDiv = document.getElementById('advancedTablePropsAnalysis');
    const rouletteWheelSvgContainer = document.getElementById('rouletteWheelSvgContainer');
    const neighborAnalysisDisplayDiv = document.getElementById('neighborAnalysisDisplay');
    const wheelDistanceDisplayDiv = document.getElementById('wheelDistanceDisplay');
    const sectorMovementDisplayDiv = document.getElementById('sectorMovementDisplay');
    const diagonalAnalysisDisplayDiv = document.getElementById('diagonalAnalysisDisplay');
    const quadrantAnalysisDisplayDiv = document.getElementById('quadrantAnalysisDisplay');
    const streetTrendsDisplayDiv = document.getElementById('streetTrendsDisplay');
    const columnTrendsDisplayDiv = document.getElementById('columnTrendsDisplay');
    const digitSumAnalysisDisplayDiv = document.getElementById('digitSumAnalysisDisplay');
    const mirrorNumberAnalysisDisplayDiv = document.getElementById('mirrorNumberAnalysisDisplay');
    const symmetrySetAnalysisDisplayDiv = document.getElementById('symmetrySetAnalysisDisplay'); // Added
    const userDefinedSetsDisplayDiv = document.getElementById('userDefinedSetsDisplay'); // Added

    let results = [];
    let numberCounts = {};
    let lastSeenAtSpin = {};
    let appearanceIndexes = {};

    const HOT_COLD_RANGE = 20; const HOT_COUNT = 3; const COLD_COUNT = 3; const SLEEPER_THRESHOLD = 35;

    const RED_NUMBERS = [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36];
    const BLACK_NUMBERS = [2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35];
    const DOZENS = {'1st Dozen':{min:1,max:12,numbers:Array.from({length:12},(_,i)=>i+1)},'2nd Dozen':{min:13,max:24,numbers:Array.from({length:12},(_,i)=>i+13)},'3rd Dozen':{min:25,max:36,numbers:Array.from({length:12},(_,i)=>i+25)}};
    const COLUMNS = {'Column 1':[1,4,7,10,13,16,19,22,25,28,31,34],'Column 2':[2,5,8,11,14,17,20,23,26,29,32,35],'Column 3':[3,6,9,12,15,18,21,24,27,30,33,36]};
    const HIGH_LOW = {'Low':{min:1,max:18},'High':{min:19,max:36}};
    const EUROPEAN_WHEEL_ORDER = [0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
    const WHEEL_NUMBER_TO_INDEX_MAP = new Map(); EUROPEAN_WHEEL_ORDER.forEach((n,i)=>WHEEL_NUMBER_TO_INDEX_MAP.set(n,i));

    let sectorHitCounts={}; let sectorLastSeenSpin={}; let currentConsecutiveSector={name:null,count:0};
    const STREETS = {}; for(let i=0;i<12;i++){const s=i*3+1;STREETS[`Street ${s}-${s+1}-${s+2}`]=[s,s+1,s+2];}
    const LINES = {}; for(let i=0;i<6;i++){const s=i*6+1;LINES[`Line ${s}-${s+5}`]=Array.from({length:6},(_,k)=>s+k);}
    const FINALES = {}; for(let i=0;i<=9;i++){FINALES[`Finale ${i}`]=[];for(let j=i;j<=36;j+=10){if(j===0&&i!==0)continue;if(j>0||(j===0&&i===0))FINALES[`Finale ${i}`].push(j);}if(FINALES[`Finale ${i}`].length===0)delete FINALES[`Finale ${i}`];}

    const DIAGONALS = {'Diag_1-5-9':[1,5,9],'Diag_2-6-10':[2,6,10],'Diag_3-7-11':[3,7,11],'Diag_4-8-12':[4,8,12],'Diag_13-17':[13,17],'Diag_14-18':[14,18],'Diag_3-5-7':[3,5,7],'Diag_2-4':[2,4],'Diag_1':[1],'Diag_6-8-10':[6,8,10],'Diag_9-11-13':[9,11,13]};
    const QUADRANTS = {'Quadrant 1 (1-9)':Array.from({length:9},(_,i)=>i+1),'Quadrant 2 (10-18)':Array.from({length:9},(_,i)=>i+10),'Quadrant 3 (19-27)':Array.from({length:9},(_,i)=>i+19),'Quadrant 4 (28-36)':Array.from({length:9},(_,i)=>i+28)};
    let streetStats={}; let columnStats={}; let diagonalStats={}; let quadrantStats={};
    let currentConsecutiveStreet={name:null,count:0}; let currentConsecutiveColumn={name:null,count:0}; let currentConsecutiveDiagonal={name:null,count:0}; let currentConsecutiveQuadrant={name:null,count:0};

    const MIRROR_PAIRS_DEF = {12:21,13:31,23:32};
    function getMirrorPairKey(num){const m=MIRROR_PAIRS_DEF[num];if(m)return num<m?`${num}/${m}`:`${m}/${num}`;for(const k in MIRROR_PAIRS_DEF)if(MIRROR_PAIRS_DEF[k]===num){const pk=parseInt(k);return num<pk?`${num}/${pk}`:`${pk}/${num}`;}return null;}
    const SYMMETRY_SETS = {'Table Half 1-18':Array.from({length:18},(_,i)=>i+1),'Table Half 19-36':Array.from({length:18},(_,i)=>i+19)};
    const USER_DEFINED_SETS = {'Favorite Set Alpha':[3,17,25,34],'Hot Neighbors of 0':[0,32,15,26,3]};
    let digitSumStats={}; let mirrorPairStats={}; let symmetrySetStats={}; let userSetStats={};
    let currentConsecutiveDigitSum={group:null,count:0}; let currentConsecutiveMirrorPair={pairName:null,count:0}; let currentConsecutiveSymmetrySet={setName:null,count:0}; let currentConsecutiveUserSet={setName:null,count:0};

    const WHEEL_NUMBERS = {'Voisins du Zéro':[22,18,29,7,28,12,35,3,26,0,32,15,19,4,21,2,25],'Tiers du Cylindre':[27,13,36,11,30,8,23,10,5,24,16,33],'Orphelins':[17,34,6,1,20,14,31,9],'Zero Spiel':[12,35,3,26,0,32,15]};

    function initializeNumberCounts(){numberCounts={};for(let i=0;i<=36;i++)numberCounts[i]=0;}
    function initializeLastSeen(){lastSeenAtSpin={};for(let i=0;i<=36;i++)lastSeenAtSpin[i]=-1;}
    function initializeAppearanceIndexes(){appearanceIndexes={};for(let i=0;i<=36;i++)appearanceIndexes[i]=[];}
    function initializeSectorStats(){sectorHitCounts={};sectorLastSeenSpin={};currentConsecutiveSector={name:null,count:0};for(const n in WHEEL_NUMBERS){sectorHitCounts[n]=0;sectorLastSeenSpin[n]=-1;}}
    function initializeTableClusterStats(){streetStats={};for(const n in STREETS)streetStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveStreet={name:null,count:0};columnStats={};for(const n in COLUMNS)columnStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveColumn={name:null,count:0};diagonalStats={};for(const n in DIAGONALS)diagonalStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveDiagonal={name:null,count:0};quadrantStats={};for(const n in QUADRANTS)quadrantStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveQuadrant={name:null,count:0};}
    function initializeCustomGroupStats(){digitSumStats={};for(let i=1;i<=9;i++)digitSumStats[i]={hitCount:0,lastSeenSpin:-1};currentConsecutiveDigitSum={group:null,count:0};mirrorPairStats={};for(const k in MIRROR_PAIRS_DEF){const pk=getMirrorPairKey(parseInt(k));if(pk&&!mirrorPairStats[pk])mirrorPairStats[pk]={hitCount:0,lastSeenSpin:-1};}currentConsecutiveMirrorPair={pairName:null,count:0};symmetrySetStats={};for(const n in SYMMETRY_SETS)symmetrySetStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveSymmetrySet={setName:null,count:0};userSetStats={};for(const n in USER_DEFINED_SETS)userSetStats[n]={hitCount:0,lastSeenSpin:-1};currentConsecutiveUserSet={setName:null,count:0};}

    initializeNumberCounts(); initializeLastSeen(); initializeAppearanceIndexes(); initializeSectorStats(); initializeTableClusterStats(); initializeCustomGroupStats();

    function calculateDigitSum(n){if(n===0)return null;if(n<0||n>36)return null;let s=n;while(s>9){s=String(s).split('').reduce((a,d)=>a+parseInt(d),0);}return s;}
    function getWheelNeighbors(cn,md=2){if(cn===null||cn===undefined||!WHEEL_NUMBER_TO_INDEX_MAP.has(cn))return{};const ci=WHEEL_NUMBER_TO_INDEX_MAP.get(cn);const ws=EUROPEAN_WHEEL_ORDER.length;const n={};for(let d=1;d<=md;d++){n[`plus${d}`]=EUROPEAN_WHEEL_ORDER[(ci+d)%ws];n[`minus${d}`]=EUROPEAN_WHEEL_ORDER[(ci-d+ws)%ws];}return n;}
    function calculateWheelDistance(pn,cn){if(pn===null||cn===null||!WHEEL_NUMBER_TO_INDEX_MAP.has(pn)||!WHEEL_NUMBER_TO_INDEX_MAP.has(cn))return{distance:null,direction:'N/A'};const pi=WHEEL_NUMBER_TO_INDEX_MAP.get(pn);const ci=WHEEL_NUMBER_TO_INDEX_MAP.get(cn);const ws=EUROPEAN_WHEEL_ORDER.length;let df=ci-pi;if(Math.abs(df)>ws/2)df=df>0?df-ws:df+ws;let dir=df>0?'CW':df<0?'CCW':(df===0?'Same Number':'N/A');return{distance:Math.abs(df),direction:dir,signedDistance:df};}
    function getQuadsForNumber(num){if(num===0||num>36)return[];const q=[];const c=(num-1)%3;const r=Math.floor((num-1)/3);if(c<2&&r<11)q.push(`Quad: ${num}, ${num+1}, ${num+3}, ${num+4}`);if(c>0&&r<11)q.push(`Quad: ${num-1}, ${num}, ${num+2}, ${num+3}`);if(c<2&&r>0)q.push(`Quad: ${num-3}, ${num-2}, ${num}, ${num+1}`);if(c>0&&r>0)q.push(`Quad: ${num-4}, ${num-3}, ${num-1}, ${num}`);return q.sort();}

    function updateDisplay(dD,cG){if(!dD){console.error(`${dD?dD.id:'Unknown'} not found`);return;}let c=dD.querySelector('.content');if(!c){console.error('Missing .content div in',dD.id);c=document.createElement('div');c.className='content';dD.appendChild(c);}c.innerHTML='';cG(c);}
    function updateHitFrequencyDisplay(){updateDisplay(hitFrequencyDiv,(c)=>{const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding:0;margin:0;max-height:150px;overflow-y:auto;border:1px solid #eee;padding:5px;";for(let i=0;i<=36;i++){const li=document.createElement('li');li.textContent=`Number ${i}: ${numberCounts[i]} time(s)`;li.style.padding='2px 0';ul.appendChild(li);}c.appendChild(ul);});}
    function updateHotColdAnalysis(){updateDisplay(hotColdDiv,(c)=>{const rel=results.slice(-HOT_COLD_RANGE);if(rel.length===0){c.textContent='Not enough data.';return;}const rc={};for(let i=0;i<=36;i++)rc[i]=0;rel.forEach(n=>rc[n]++);const nbf=[];for(let i=0;i<=36;i++)nbf.push({n:i,c:rc[i]});nbf.sort((a,b)=>b.c===a.c?a.n-b.n:b.c-a.c);const hot=nbf.slice(0,HOT_COUNT).filter(i=>i.c>0);nbf.sort((a,b)=>a.c===b.c?a.n-b.n:a.c-b.c);const cold=nbf.slice(0,COLD_COUNT);const hp=document.createElement('p');hp.innerHTML=`<strong>Hot (last ${HOT_COLD_RANGE}):</strong> ${hot.length>0?hot.map(i=>`${i.n} (${i.c}x)`).join(', '):'N/A'}`;c.appendChild(hp);const cp=document.createElement('p');cp.innerHTML=`<strong>Cold (last ${HOT_COLD_RANGE}):</strong> ${cold.length>0?cold.map(i=>`${i.n} (${i.c}x)`).join(', '):'N/A'}`;c.appendChild(cp);});}
    function updateLastSeenDisplay(){updateDisplay(lastSeenDiv,(c)=>{if(results.length===0){c.innerHTML='<p>No results yet.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding:0;margin:0;max-height:150px;overflow-y:auto;border:1px solid #eee;padding:5px;";const csi=results.length-1;for(let i=0;i<=36;i++){const li=document.createElement('li');li.style.padding='2px 0';if(lastSeenAtSpin[i]!==-1){const sa=csi-lastSeenAtSpin[i];li.textContent=`Number ${i}: seen ${sa===0?"this spin":`${sa} spin(s) ago`}`; }else{li.textContent=`Number ${i}: never seen`;}ul.appendChild(li);}c.appendChild(ul);});}
    function updateRepeatersAnalysis(){updateDisplay(repeaterSleepersDiv.querySelector('.repeaters-section')||repeaterSleepersDiv,(c)=>{if(results.length<2){c.textContent='Not enough data.';return;}const lN=results[results.length-1];const pN=results[results.length-2];if(lN===pN){const p=document.createElement('p');p.style.color='green';p.innerHTML=`<strong>Direct Repeater!</strong> Number ${lN} appeared consecutively.`;c.appendChild(p);}else{c.textContent='No direct repeater.';}});}
    function updateSleepersAnalysis(){updateDisplay(repeaterSleepersDiv.querySelector('.sleepers-section')||repeaterSleepersDiv,(c)=>{if(results.length===0){c.textContent='No results yet.';return;}const slp=[];const csi=results.length-1;for(let i=0;i<=36;i++){let sa=lastSeenAtSpin[i]!==-1?csi-lastSeenAtSpin[i]:results.length;if(sa>=SLEEPER_THRESHOLD)slp.push({n:i,sa:sa});}if(slp.length>0){const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding:0;";slp.sort((a,b)=>b.sa-a.sa);slp.forEach(s=>{const li=document.createElement('li');li.textContent=`Number ${s.n} (not seen for ${s.sa} spins)`;ul.appendChild(li);});c.appendChild(ul);}else{c.textContent=`No numbers sleeping for ${SLEEPER_THRESHOLD}+ spins.`;}});}
    function updateDistanceAnalysis(){updateDisplay(distanceAnalysisDiv,(c)=>{if(results.length<2){c.innerHTML='<p>Not enough data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding:0;margin:0;max-height:150px;overflow-y:auto;border:1px solid #eee;padding:5px;";let fg=false;for(let i=0;i<=36;i++){const ap=appearanceIndexes[i];if(ap&&ap.length>=2){fg=true;const gps=[];for(let j=1;j<ap.length;j++)gps.push((ap[j]-ap[j-1])-1);const li=document.createElement('li');li.style.padding='2px 0';li.textContent=`Number ${i}: Gaps [${gps.join(', ')}]`;ul.appendChild(li);}}if(!fg)c.textContent='No numbers repeated yet.';else c.appendChild(ul);});}
    function analyzeNumber(number){latestNumberAnalysisDiv.innerHTML='';const at=document.createElement('p');at.innerHTML=`Analysis for <strong>${number}</strong> (Wheel Sectors):`;latestNumberAnalysisDiv.appendChild(at);let bs=[];for(const gn in WHEEL_NUMBERS)if(WHEEL_NUMBERS[gn].includes(number)){const gp=document.createElement('p');gp.textContent=`Belongs to: ${gn}`;latestNumberAnalysisDiv.appendChild(gp);bs.push(gn);}if(bs.length===0&&(number!==null&&number!==undefined)){const ngp=document.createElement('p');ngp.textContent='Not part of any major predefined wheel-based group.';latestNumberAnalysisDiv.appendChild(ngp);}else if(number===null||number===undefined)latestNumberAnalysisDiv.innerHTML='<p>No number selected.</p>';if(rouletteWheelSvgContainer){const he=rouletteWheelSvgContainer.querySelectorAll('.highlighted-svg-number');he.forEach(el=>el.classList.remove('highlighted-svg-number'));if(bs.length>0)bs.forEach(sn=>{const nis=WHEEL_NUMBERS[sn];if(nis)nis.forEach(nins=>{const se=rouletteWheelSvgContainer.querySelector(`#svg-num-${nins}`);if(se)se.classList.add('highlighted-svg-number');});});else if(number!==null&&number!==undefined){const sse=rouletteWheelSvgContainer.querySelector(`#svg-num-${number}`);if(sse)sse.classList.add('highlighted-svg-number');}}}
    function updateTableGroupAnalysis(num){const ca=(typeof num==='number')?num:(results.length>0?results[results.length-1]:null);updateDisplay(basicPropsDiv,(c)=>{if(ca===null){c.innerHTML='<p>No number selected.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="padding-left:0;list-style-type:none;";let eoT='N/A (0)';if(ca>0)eoT=(ca%2===0)?'Even':'Odd';const eol=document.createElement('li');eol.textContent=`Even/Odd: ${eoT}`;ul.appendChild(eol);let ct='Green (0)';if(RED_NUMBERS.includes(ca))ct='Red';else if(BLACK_NUMBERS.includes(ca))ct='Black';const rbl=document.createElement('li');rbl.textContent=`Color: ${ct}`;ul.appendChild(rbl);let hlT='N/A (0)';if(ca>=HIGH_LOW.Low.min&&ca<=HIGH_LOW.Low.max)hlT='Low (1-18)';else if(ca>=HIGH_LOW.High.min&&ca<=HIGH_LOW.High.max)hlT='High (19-36)';const hll=document.createElement('li');hll.textContent=`Range: ${hlT}`;ul.appendChild(hll);c.appendChild(ul);});updateDisplay(positionalPropsDiv,(c)=>{if(ca===null){c.innerHTML='<p>No number selected.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="padding-left:0;list-style-type:none;";let dT='N/A (0)';if(ca>0)for(const dn in DOZENS)if(ca>=DOZENS[dn].min&&ca<=DOZENS[dn].max){dT=dn;break;}const dzl=document.createElement('li');dzl.textContent=`Dozen: ${dT}`;ul.appendChild(dzl);let clT='N/A (0)';if(ca>0)for(const cn in COLUMNS)if(COLUMNS[cn].includes(ca)){clT=cn;break;}const cll=document.createElement('li');cll.textContent=`Column: ${clT}`;ul.appendChild(cll);c.appendChild(ul);});updateDisplay(advancedTablePropsDiv,(c)=>{if(ca===null){c.innerHTML='<p>No number selected.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="padding-left:0;list-style-type:none;";let stT='N/A (0)';if(ca>0)for(const sn in STREETS)if(STREETS[sn].includes(ca)){stT=sn;break;}const stl=document.createElement('li');stl.textContent=`Street: ${stT}`;ul.appendChild(stl);let lnT='N/A (0)';if(ca>0)for(const ln in LINES)if(LINES[ln].includes(ca)){lnT=ln;break;}const lnl=document.createElement('li');lnl.textContent=`Line: ${lnT}`;ul.appendChild(lnl);const qdl=document.createElement('li');if(ca>0){const qds=getQuadsForNumber(ca);qdl.textContent=`Corners: ${qds.length>0?qds.join(', '):'None'}`;}else qdl.textContent='Corners: N/A (0)';ul.appendChild(qdl);let fiT='N/A (0)';let ff=false;if(FINALES[`Finale ${ca%10}`]&&FINALES[`Finale ${ca%10}`].includes(ca)){fiT=`Finale ${ca%10}`;ff=true;}else if(ca===0&&FINALES['Finale 0']&&FINALES['Finale 0'].includes(0)){fiT='Finale 0';ff=true;}if(!ff&&ca!==null&&ca!==undefined)fiT='None';else if(ca===null||ca===undefined)fiT='No number selected';const fil=document.createElement('li');fil.textContent=`Finale: ${fiT}`;ul.appendChild(fil);c.appendChild(ul);});}
    function updateNeighborAnalysisDisplay(cn){updateDisplay(neighborAnalysisDisplayDiv,(c)=>{if(cn===null||cn===undefined){c.innerHTML='<p>No number selected.</p>';return;}const n=getWheelNeighbors(cn,2);const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";if(Object.keys(n).length===0){const li=document.createElement('li');li.textContent='Could not determine neighbors.';ul.appendChild(li);}else{const l1=document.createElement('li');l1.innerHTML=`<strong>&pm;1:</strong> ${n.minus1} (CCW), ${n.plus1} (CW)`;ul.appendChild(l1);const l2=document.createElement('li');l2.innerHTML=`<strong>&pm;2:</strong> ${n.minus2} (CCW), ${n.plus2} (CW)`;ul.appendChild(l2);} c.appendChild(ul);});}
    function updateWheelDistanceDisplay(cn,pn){updateDisplay(wheelDistanceDisplayDiv,(c)=>{if(pn===null||cn===null){c.innerHTML='<p>Not enough data (need 2+ spins).</p>';return;}const r=calculateWheelDistance(pn,cn);const p=document.createElement('p');if(r.distance===null)p.textContent='Could not calculate.';else if(r.direction==='Same Number')p.textContent=`Prev: ${pn}, Curr: ${cn} (Same Num).`;else p.textContent=`From ${pn} to ${cn}: ${r.distance} pockets ${r.direction}.`;c.appendChild(p);});}
    function updateSectorMovementDisplay(cn,pn,cs){updateDisplay(sectorMovementDisplayDiv,(c)=>{const oE=[];if(cn===null&&pn===null){const p=document.createElement('p');p.textContent="No data.";oE.push(p);}else{const pi=document.createElement('p');pi.textContent=`Latest: ${cn!==null?cn:'N/A'}`;oE.push(pi);const pm=document.createElement('p');if(pn!==null&&cn!==null){const m=calculateWheelDistance(pn,cn);if(m.distance!==null&&m.direction!=='Same Number')pm.textContent=`Movement: ${m.distance} pkts ${m.direction}.`;else if(m.direction==='Same Number')pm.textContent=`Movement: Same number.`;else pm.textContent="Movement: N/A";}else if(cn!==null)pm.textContent="Movement: First spin.";else pm.textContent="Movement: N/A";oE.push(pm);if(currentConsecutiveSector.name&&currentConsecutiveSector.count>1){const pc=document.createElement('p');pc.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveSector.count} in ${currentConsecutiveSector.name}.`;oE.push(pc);}const pt=document.createElement('p');pt.innerHTML='<strong>Sector Stats:</strong>';oE.push(pt);const uh=document.createElement('ul');uh.style.cssText="list-style-type:none;padding-left:0;";if(results.length>0){const csi=results.length-1;const ss=Object.keys(WHEEL_NUMBERS).sort((a,b)=>{if(sectorHitCounts[b]!==sectorHitCounts[a])return sectorHitCounts[b]-sectorHitCounts[a];return sectorLastSeenSpin[b]-sectorLastSeenSpin[a];});ss.forEach(sn=>{let rt="never seen";if(sectorLastSeenSpin[sn]!==-1){const sa=csi-sectorLastSeenSpin[sn];rt=sa===0&&cs&&cs.includes(sn)?"this spin":`${sa} spins ago`;}const li=document.createElement('li');li.textContent=`${sn}: ${sectorHitCounts[sn]} hits (Last: ${rt})`;uh.appendChild(li);});}else{const li=document.createElement('li');li.textContent="No results for sector stats.";uh.appendChild(li);}oE.push(uh);} oE.forEach(el=>c.appendChild(el));});}
    function updateDiagonalAnalysisDisplay(cnfa){updateDisplay(diagonalAnalysisDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const dn in DIAGONALS){const li=document.createElement('li');const st=diagonalStats[dn]||{hitCount:0,lastSeenSpin:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&DIAGONALS[dn]&&DIAGONALS[dn].includes(cnfa)?"this spin":`${sa} spins ago`;}li.textContent=`${dn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveDiagonal.name&&currentConsecutiveDiagonal.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveDiagonal.count} in ${currentConsecutiveDiagonal.name}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateQuadrantAnalysisDisplay(cnfa){updateDisplay(quadrantAnalysisDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const qn in QUADRANTS){const li=document.createElement('li');const st=quadrantStats[qn]||{hitCount:0,lastSeenSpin:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&QUADRANTS[qn]&&QUADRANTS[qn].includes(cnfa)?"this spin":`${sa} spins ago`;}li.textContent=`${qn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveQuadrant.name&&currentConsecutiveQuadrant.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveQuadrant.count} in ${currentConsecutiveQuadrant.name}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateStreetTrendsDisplay(cnfa){updateDisplay(streetTrendsDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const sn in STREETS){const li=document.createElement('li');const st=streetStats[sn]||{hitCount:0,lastSeenSpin:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&STREETS[sn]&&STREETS[sn].includes(cnfa)?"this spin":`${sa} spins ago`;}li.textContent=`${sn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveStreet.name&&currentConsecutiveStreet.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveStreet.count} in ${currentConsecutiveStreet.name}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateColumnTrendsDisplay(cnfa){updateDisplay(columnTrendsDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const cn in COLUMNS){const li=document.createElement('li');const st=columnStats[cn]||{hitCount:0,lastSeenSpin:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&COLUMNS[cn]&&COLUMNS[cn].includes(cnfa)?"this spin":`${sa} spins ago`;}li.textContent=`${cn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveColumn.name&&currentConsecutiveColumn.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveColumn.count} in ${currentConsecutiveColumn.name}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateDigitSumDisplay(cnfa){updateDisplay(digitSumAnalysisDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;const cnd=cnfa!==null?calculateDigitSum(cnfa):null;for(let i=1;i<=9;i++){const li=document.createElement('li');const st=digitSumStats[i]||{hitCount:0,lastSeenSpin:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&cnd===i?"this spin":`${sa} spins ago`;}li.textContent=`Digit Sum Group ${i}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveDigitSum.group&&currentConsecutiveDigitSum.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveDigitSum.count} hits in Group ${currentConsecutiveDigitSum.group}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateMirrorNumberDisplay(cnfa){updateDisplay(mirrorNumberAnalysisDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;const cnk=cnfa!==null?getMirrorPairKey(cnfa):null;for(const pk in mirrorPairStats){const li=document.createElement('li');const st=mirrorPairStats[pk];let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&cnk===pk?"hit this spin":`${sa} spins ago`;}li.textContent=`Mirror Pair ${pk}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveMirrorPair.pairName&&currentConsecutiveMirrorPair.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveMirrorPair.count} hits for pair ${currentConsecutiveMirrorPair.pairName}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateSymmetrySetsDisplay(cnfa){updateDisplay(symmetrySetAnalysisDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const sn in SYMMETRY_SETS){const li=document.createElement('li');const st=symmetrySetStats[sn]||{hc:0,lss:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&SYMMETRY_SETS[sn]&&SYMMETRY_SETS[sn].includes(cnfa)?"hit this spin":`${sa} spins ago`;}li.textContent=`${sn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveSymmetrySet.setName&&currentConsecutiveSymmetrySet.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveSymmetrySet.count} in ${currentConsecutiveSymmetrySet.setName}.`;ul.appendChild(sl);}c.appendChild(ul);});}
    function updateUserSetsDisplay(cnfa){updateDisplay(userDefinedSetsDisplayDiv,(c)=>{if(cnfa===null&&results.length===0){c.innerHTML='<p>No data.</p>';return;}const ul=document.createElement('ul');ul.style.cssText="list-style-type:none;padding-left:0;";const csi=results.length>0?results.length-1:0;for(const sn in USER_DEFINED_SETS){const li=document.createElement('li');const st=userSetStats[sn]||{hc:0,lss:-1};let rt="never seen";if(st.lastSeenSpin!==-1){const sa=csi-st.lastSeenSpin;rt=sa===0&&USER_DEFINED_SETS[sn]&&USER_DEFINED_SETS[sn].includes(cnfa)?"hit this spin":`${sa} spins ago`;}li.textContent=`${sn}: ${st.hitCount} hits (Last: ${rt})`;ul.appendChild(li);}if(currentConsecutiveUserSet.setName&&currentConsecutiveUserSet.count>1){const sl=document.createElement('li');sl.innerHTML=`<strong>Streak:</strong> ${currentConsecutiveUserSet.count} in ${currentConsecutiveUserSet.setName}.`;ul.appendChild(sl);}c.appendChild(ul);});}


    // Main application logic
    addNumberBtn.addEventListener('click', addNumber);
    resetBtn.addEventListener('click', resetResults);
    numberInput.addEventListener('keypress', (event) => { if (event.key === 'Enter') addNumber(); });

    function addNumber() {
        const numberStr = numberInput.value;
        if (numberStr === '') { alert('Please enter a number.'); return; }
        const number = parseInt(numberStr);
        if (isNaN(number) || number < 0 || number > 36) { alert('Please enter a valid number (0-36).'); numberInput.value=''; return; }

        results.push(number);
        numberCounts[number]++;
        lastSeenAtSpin[number] = results.length - 1;
        if (!appearanceIndexes[number]) appearanceIndexes[number] = [];
        appearanceIndexes[number].push(results.length - 1);

        let belongingSectorsForCurrent = [];
        for (const groupName in WHEEL_NUMBERS) { if (WHEEL_NUMBERS[groupName].includes(number)) belongingSectorsForCurrent.push(groupName); }
        belongingSectorsForCurrent.forEach(sectorName => { sectorHitCounts[sectorName]++; sectorLastSeenSpin[sectorName] = results.length - 1; });
        let streakContinuedSector = false; if (currentConsecutiveSector.name && belongingSectorsForCurrent.includes(currentConsecutiveSector.name)) { currentConsecutiveSector.count++; streakContinuedSector = true; } if (!streakContinuedSector) { if (belongingSectorsForCurrent.length > 0) { currentConsecutiveSector.name = belongingSectorsForCurrent[0]; currentConsecutiveSector.count = 1; } else { currentConsecutiveSector.name = null; currentConsecutiveSector.count = 0; } }

        let hitStreet=false; if(number>0)for(const sn in STREETS)if(STREETS[sn].includes(number)){hitStreet=true;if(!streetStats[sn])streetStats[sn]={hitCount:0,lastSeenSpin:-1};streetStats[sn].hitCount++;streetStats[sn].lastSeenSpin=results.length-1;if(currentConsecutiveStreet.name===sn)currentConsecutiveStreet.count++;else{currentConsecutiveStreet.name=sn;currentConsecutiveStreet.count=1;}break;} if(!hitStreet)currentConsecutiveStreet={name:null,count:0};
        let hitCol=false; if(number>0)for(const cn in COLUMNS)if(COLUMNS[cn].includes(number)){hitCol=true;if(!columnStats[cn])columnStats[cn]={hitCount:0,lastSeenSpin:-1};columnStats[cn].hitCount++;columnStats[cn].lastSeenSpin=results.length-1;if(currentConsecutiveColumn.name===cn)currentConsecutiveColumn.count++;else{currentConsecutiveColumn.name=cn;currentConsecutiveColumn.count=1;}break;} if(!hitCol)currentConsecutiveColumn={name:null,count:0};
        let hitDiag=false; let lhdn=null; for(const dn in DIAGONALS)if(DIAGONALS[dn].includes(number)){hitDiag=true;lhdn=dn;if(!diagonalStats[dn])diagonalStats[dn]={hitCount:0,lastSeenSpin:-1};diagonalStats[dn].hitCount++;diagonalStats[dn].lastSeenSpin=results.length-1;} if(lhdn){if(currentConsecutiveDiagonal.name===lhdn)currentConsecutiveDiagonal.count++;else{currentConsecutiveDiagonal.name=lhdn;currentConsecutiveDiagonal.count=1;}}else if(!hitDiag)currentConsecutiveDiagonal={name:null,count:0};
        let hitQuad=false; if(number>0)for(const qn in QUADRANTS)if(QUADRANTS[qn].includes(number)){hitQuad=true;if(!quadrantStats[qn])quadrantStats[qn]={hitCount:0,lastSeenSpin:-1};quadrantStats[qn].hitCount++;quadrantStats[qn].lastSeenSpin=results.length-1;if(currentConsecutiveQuadrant.name===qn)currentConsecutiveQuadrant.count++;else{currentConsecutiveQuadrant.name=qn;currentConsecutiveQuadrant.count=1;}break;} if(!hitQuad&&number>0)currentConsecutiveQuadrant={name:null,count:0}; else if(number===0)currentConsecutiveQuadrant={name:null,count:0};
        const dsGroup = calculateDigitSum(number); if(dsGroup){if(!digitSumStats[dsGroup])digitSumStats[dsGroup]={hitCount:0,lastSeenSpin:-1};digitSumStats[dsGroup].hitCount++; digitSumStats[dsGroup].lastSeenSpin=results.length-1; if(currentConsecutiveDigitSum.group===dsGroup)currentConsecutiveDigitSum.count++; else {currentConsecutiveDigitSum.group=dsGroup; currentConsecutiveDigitSum.count=1;}} else currentConsecutiveDigitSum={group:null,count:0};
        const mirrorPairKey = getMirrorPairKey(number); if(mirrorPairKey){if(!mirrorPairStats[mirrorPairKey])mirrorPairStats[mirrorPairKey]={hitCount:0,lastSeenSpin:-1};mirrorPairStats[mirrorPairKey].hitCount++;mirrorPairStats[mirrorPairKey].lastSeenSpin=results.length-1;if(currentConsecutiveMirrorPair.pairName===mirrorPairKey)currentConsecutiveMirrorPair.count++;else{currentConsecutiveMirrorPair.pairName=mirrorPairKey;currentConsecutiveMirrorPair.count=1;}}else currentConsecutiveMirrorPair={pairName:null,count:0};
        let hitAnySymm=false; let lhsn=null; for(const sn in SYMMETRY_SETS)if(SYMMETRY_SETS[sn].includes(number)){hitAnySymm=true;lhsn=sn;if(!symmetrySetStats[sn])symmetrySetStats[sn]={hitCount:0,lastSeenSpin:-1};symmetrySetStats[sn].hitCount++;symmetrySetStats[sn].lastSeenSpin=results.length-1;} if(lhsn){if(currentConsecutiveSymmetrySet.setName===lhsn)currentConsecutiveSymmetrySet.count++;else{currentConsecutiveSymmetrySet.setName=lhsn;currentConsecutiveSymmetrySet.count=1;}}else currentConsecutiveSymmetrySet={setName:null,count:0};
        let hitAnyUser=false; let lhun=null; for(const sn in USER_DEFINED_SETS)if(USER_DEFINED_SETS[sn].includes(number)){hitAnyUser=true;lhun=sn;if(!userSetStats[sn])userSetStats[sn]={hitCount:0,lastSeenSpin:-1};userSetStats[sn].hitCount++;userSetStats[sn].lastSeenSpin=results.length-1;} if(lhun){if(currentConsecutiveUserSet.setName===lhun)currentConsecutiveUserSet.count++;else{currentConsecutiveUserSet.setName=lhun;currentConsecutiveUserSet.count=1;}}else currentConsecutiveUserSet={setName:null,count:0};

        renderResults();
        saveResults();

        analyzeNumber(number); updateHitFrequencyDisplay(); updateHotColdAnalysis(); updateLastSeenDisplay(); updateRepeatersAnalysis(); updateSleepersAnalysis(); updateDistanceAnalysis();
        updateTableGroupAnalysis(number); updateNeighborAnalysisDisplay(number); const prevNumber = results.length >= 2 ? results[results.length - 2] : null; updateWheelDistanceDisplay(number, prevNumber); updateSectorMovementDisplay(number, prevNumber, belongingSectorsForCurrent);
        updateDiagonalAnalysisDisplay(number); updateQuadrantAnalysisDisplay(number); updateStreetTrendsDisplay(number); updateColumnTrendsDisplay(number); updateDigitSumDisplay(number); updateMirrorNumberDisplay(number);
        updateSymmetrySetsDisplay(number); updateUserSetsDisplay(number);


        numberInput.value = '';
        numberInput.focus();
    }

    function renderResults() { resultsList.innerHTML = ''; results.forEach(r => { const li = document.createElement('li'); li.textContent = r; resultsList.appendChild(li); }); resultsList.scrollTop = resultsList.scrollHeight; }
    function saveResults() { localStorage.setItem('rouletteResults', JSON.stringify(results)); }
    function clearAnalysis() { latestNumberAnalysisDiv.innerHTML = ''; if (rouletteWheelSvgContainer) { const hEls = rouletteWheelSvgContainer.querySelectorAll('.highlighted-svg-number'); hEls.forEach(el => el.classList.remove('highlighted-svg-number')); } }

    function resetResults() {
        if (confirm('Are you sure you want to reset all results?')) {
            results = [];
            initializeNumberCounts(); initializeLastSeen(); initializeAppearanceIndexes(); initializeSectorStats(); initializeTableClusterStats(); initializeCustomGroupStats();
            renderResults(); clearAnalysis();
            updateHitFrequencyDisplay(); updateHotColdAnalysis(); updateLastSeenDisplay(); updateRepeatersAnalysis(); updateSleepersAnalysis(); updateDistanceAnalysis();
            updateTableGroupAnalysis(null); updateNeighborAnalysisDisplay(null); updateWheelDistanceDisplay(null, null); updateSectorMovementDisplay(null, null, []);
            updateDiagonalAnalysisDisplay(null); updateQuadrantAnalysisDisplay(null); updateStreetTrendsDisplay(null); updateColumnTrendsDisplay(null); updateDigitSumDisplay(null); updateMirrorNumberDisplay(null);
            updateSymmetrySetsDisplay(null); updateUserSetsDisplay(null);
            localStorage.removeItem('rouletteResults');
        }
    }

    function loadResults() {
        const storedResults = localStorage.getItem('rouletteResults');
        initializeNumberCounts(); initializeLastSeen(); initializeAppearanceIndexes(); initializeSectorStats(); initializeTableClusterStats(); initializeCustomGroupStats();
        if (storedResults) {
            results = JSON.parse(storedResults);
            results.forEach((num, index) => {
                numberCounts[num]++;
                lastSeenAtSpin[num] = index;
                if (!appearanceIndexes[num]) appearanceIndexes[num] = [];
                appearanceIndexes[num].push(index);

                let bSectors = []; for(const gn in WHEEL_NUMBERS) if(WHEEL_NUMBERS[gn].includes(num))bSectors.push(gn);
                bSectors.forEach(sn=>{sectorHitCounts[sn]++; sectorLastSeenSpin[sn]=index;});
                let strkContSec=false; if(currentConsecutiveSector.name&&bSectors.includes(currentConsecutiveSector.name)){currentConsecutiveSector.count++;strkContSec=true;} if(!strkContSec){if(bSectors.length>0){currentConsecutiveSector.name=bSectors[0];currentConsecutiveSector.count=1;}else currentConsecutiveSector={name:null,count:0};}

                let hitStr=false; if(num>0)for(const sn in STREETS)if(STREETS[sn].includes(num)){hitStr=true;if(!streetStats[sn])streetStats[sn]={hitCount:0,lastSeenSpin:-1};streetStats[sn].hitCount++;streetStats[sn].lastSeenSpin=index;if(currentConsecutiveStreet.name===sn)currentConsecutiveStreet.count++;else{currentConsecutiveStreet.name=sn;currentConsecutiveStreet.count=1;}break;} if(!hitStr)currentConsecutiveStreet={name:null,count:0};
                let hitCol=false; if(num>0)for(const cn in COLUMNS)if(COLUMNS[cn].includes(num)){hitCol=true;if(!columnStats[cn])columnStats[cn]={hitCount:0,lastSeenSpin:-1};columnStats[cn].hitCount++;columnStats[cn].lastSeenSpin=index;if(currentConsecutiveColumn.name===cn)currentConsecutiveColumn.count++;else{currentConsecutiveColumn.name=cn;currentConsecutiveColumn.count=1;}break;} if(!hitCol)currentConsecutiveColumn={name:null,count:0};
                let hitDg=false;let lhDn=null;for(const dn in DIAGONALS)if(DIAGONALS[dn].includes(num)){hitDg=true;lhDn=dn;if(!diagonalStats[dn])diagonalStats[dn]={hitCount:0,lastSeenSpin:-1};diagonalStats[dn].hitCount++;diagonalStats[dn].lastSeenSpin=index;} if(lhDn){if(currentConsecutiveDiagonal.name===lhDn)currentConsecutiveDiagonal.count++;else{currentConsecutiveDiagonal.name=lhDn;currentConsecutiveDiagonal.count=1;}}else if(!hitDg)currentConsecutiveDiagonal={name:null,count:0};
                let hitQd=false; if(num>0)for(const qn in QUADRANTS)if(QUADRANTS[qn].includes(num)){hitQd=true;if(!quadrantStats[qn])quadrantStats[qn]={hitCount:0,lastSeenSpin:-1};quadrantStats[qn].hitCount++;quadrantStats[qn].lastSeenSpin=index;if(currentConsecutiveQuadrant.name===qn)currentConsecutiveQuadrant.count++;else{currentConsecutiveQuadrant.name=qn;currentConsecutiveQuadrant.count=1;}break;} if(!hitQd&&num>0)currentConsecutiveQuadrant={name:null,count:0}; else if(num===0)currentConsecutiveQuadrant={name:null,count:0};
                const dsg=calculateDigitSum(num); if(dsg){if(!digitSumStats[dsg])digitSumStats[dsg]={hitCount:0,lastSeenSpin:-1};digitSumStats[dsg].hitCount++;digitSumStats[dsg].lastSeenSpin=index;if(currentConsecutiveDigitSum.group===dsg)currentConsecutiveDigitSum.count++;else{currentConsecutiveDigitSum.group=dsg;currentConsecutiveDigitSum.count=1;}}else currentConsecutiveDigitSum={group:null,count:0};
                const mpKey=getMirrorPairKey(num);if(mpKey){if(!mirrorPairStats[mpKey])mirrorPairStats[mpKey]={hitCount:0,lastSeenSpin:-1};mirrorPairStats[mpKey].hitCount++;mirrorPairStats[mpKey].lastSeenSpin=index;if(currentConsecutiveMirrorPair.pairName===mpKey)currentConsecutiveMirrorPair.count++;else{currentConsecutiveMirrorPair.pairName=mpKey;currentConsecutiveMirrorPair.count=1;}}else currentConsecutiveMirrorPair={pairName:null,count:0};
                let ldHAnySymmSet=false;let ldLHSN=null;for(const sn in SYMMETRY_SETS)if(SYMMETRY_SETS[sn].includes(num)){ldHAnySymmSet=true;ldLHSN=sn;if(!symmetrySetStats[sn])symmetrySetStats[sn]={hitCount:0,lastSeenSpin:-1};symmetrySetStats[sn].hitCount++;symmetrySetStats[sn].lastSeenSpin=index;} if(ldLHSN){if(currentConsecutiveSymmetrySet.setName===ldLHSN)currentConsecutiveSymmetrySet.count++;else{currentConsecutiveSymmetrySet.setName=ldLHSN;currentConsecutiveSymmetrySet.count=1;}}else currentConsecutiveSymmetrySet={setName:null,count:0};
                let ldHAnyUserSet=false;let ldLHUN=null;for(const sn in USER_DEFINED_SETS)if(USER_DEFINED_SETS[sn].includes(num)){ldHAnyUserSet=true;ldLHUN=sn;if(!userSetStats[sn])userSetStats[sn]={hitCount:0,lastSeenSpin:-1};userSetStats[sn].hitCount++;userSetStats[sn].lastSeenSpin=index;} if(ldLHUN){if(currentConsecutiveUserSet.setName===ldLHUN)currentConsecutiveUserSet.count++;else{currentConsecutiveUserSet.setName=ldLHUN;currentConsecutiveUserSet.count=1;}}else currentConsecutiveUserSet={setName:null,count:0};

            });
        }
        renderResults();
        const lastNum = results.length > 0 ? results[results.length - 1] : null;
        const secondLastNum = results.length >= 2 ? results[results.length - 2] : null;
        let lastNumSectors = []; if(lastNum!==null)for(const gn in WHEEL_NUMBERS)if(WHEEL_NUMBERS[gn].includes(lastNum))lastNumSectors.push(gn);

        if (results.length > 0) analyzeNumber(lastNum); else clearAnalysis();
        updateHitFrequencyDisplay(); updateHotColdAnalysis(); updateLastSeenDisplay(); updateRepeatersAnalysis(); updateSleepersAnalysis(); updateDistanceAnalysis();
        updateTableGroupAnalysis(lastNum); updateNeighborAnalysisDisplay(lastNum); updateWheelDistanceDisplay(lastNum, secondLastNum); updateSectorMovementDisplay(lastNum, secondLastNum, lastNumSectors);
        updateDiagonalAnalysisDisplay(lastNum); updateQuadrantAnalysisDisplay(lastNum); updateStreetTrendsDisplay(lastNum); updateColumnTrendsDisplay(lastNum); updateDigitSumDisplay(lastNum); updateMirrorNumberDisplay(lastNum);
        updateSymmetrySetsDisplay(lastNum); updateUserSetsDisplay(lastNum);
    }

    loadResults(); // Initial load
});

[end of script.js]
